
* OPTIMA-IMMUTABLE-STRUCT 

+Simple+ Library that encourage the use of functional programming +
pattern matching.

It provides a wrapper for =defstruct= and a simple macro =ftype=. The symbols
are different from =cl:defstruct= and =cl:ftype= so that it avoids error in sbcl.

*NEWS*: It also provides =typevar=, one naive way to define efficient algebraic data types.

** macro defstruct (name-and-options &rest slots)

A variation of defstruct, with read-only slots and automatically defined constructor.

+ The constructor name has the different convention compared to the default naming convention in cl.
  It has (<name> &optional <slots...>) and has no keyword argument.
+ It adds read-only option in cl:defstruct to each slot definition.
+ It uses the noninterned symbols for the name of each slot, disallowing the use of slot-value.
+ It also defines a pattern matcher clause in exactly the same form as the constructor.

** macro ftype (name-or-names &rest types)

Abbreviation of =(declaim (ftype (function (<types...>) <type>)
<name-or-names...>))=.

+ =name-or-names= can be a function name or a list of function names. =setf= functions are treated correctly.
+ The last element of =types= is used for the return type.

In a smart implementation like sbcl, using =ftype= declaration is preferred
over =the= and =(declare (type ...))=.

** structue id-mixin

It has an only slot named =id= and meant to be :include-ed into the
structure. It has a fixnum value, and a random value is assigned to this
slot on each instantiation.

This is particularly important when using a hash table to avoid duplicated
evaluation. The performance of the hash function affects the rate of hash
conflict. However, SBCL yields the same sxhash value for the instances of the same
class, and results in a bad hashing result.

https://github.com/guicho271828/optima-bdd contains some usage.

** macro define-with-typevar ((typevars) &body body)

Defines a type variable. The actual instances of the structure/function can
be defined explicitly via =(instantiate-structure <struct-name>
<type-values...>)= and =(instantiate-ftype <function-name>
<type-values...>)=.

#+BEGIN_SRC lisp
#+INCLUDE example.lisp
#+END_SRC

** Dependencies

This library is at least tested on implementation listed below:

+ SBCL 1.2.8 on X86-64 Linux  3.13.0-45-generic (author's environment)

Also, it depends on the following libraries:

+ optima by Tomohiro Matsuyama ::
    Optimized Pattern Matching Library

+ alexandria by  ::
    Alexandria is a collection of portable public domain utilities.

+ iterate by  ::
    Jonathan Amsterdam's iterator/gatherer/accumulator facility



** Installation


** Author

+ Masataro Asai (guicho2.71828@gmail.com)

* Copyright

Copyright (c) 2015 Masataro Asai (guicho2.71828@gmail.com)


* License

Licensed under the LLGPL License.



